### ISSUE TITLE
Angular Callback not working

### ISSUE THREAD

**Issue by rotosonic** [pingidentity/angular-spa-sample#14]
Hello,
When I run this sample, the this.authorizationService.completeAuthorizationRequest() is never called in the callback.component.ts because the following line
https://github.com/pingidentity/angular-spa-sample/blob/master/src/app/callback/callback.component.ts#L31 causes the next step of execution to go to https://github.com/pingidentity/angular-spa-sample/blob/master/src/app/callback/callback.component.ts#L38

**Comment by dwaite** [comment]
Line 31 deals with servers which do not honor response_mode fragment, rewriting the query components into a fragment and redirecting back into the same callback callback handler.

If you are skipping the next `else if` block, that may mean that the redirect was not rewritten correctly, or did not contain the correct information originally (a `code` parameter).

Could you share the URL that the browser is requesting against the callback initially (at L31 ?)

**Comment by dwaite** [comment]
Closed due to lack of response, e.g. WORKSFORME.
