### ISSUE TITLE
index.html genration failed

### ISSUE THREAD

**Issue by skhekare** [pingidentity/angular-spa-sample#21]
× Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/icon?family=Material+Icons over the internet.
connect ETIMEDOUT 108.177.120.95:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appauth-angular-app@1.0.0 postinstall: `ng build --aot --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appauth-angular-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\azl63tz\AppData\Roaming\npm-cache\_logs\2021-05-20T11_31_07_093Z-debug.log

**Comment by dwaite** [comment]
This appears to have been a local environmental issue contacting Google to download/cache a font. If you can reproduce this issue with the latest code base, please reopen.
