### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by stephanedaviet** [pingidentity/angular-spa-sample#5]
Using Node version 8.11.3 on Linux and got the following error on `npm install`:
```
$npm install                                                                                                          16.4s  mer. 09 janv. 2019 16:28:15 CET

> appauth-angular-app@1.0.0 postinstall /media/data/workspaces/git/angular-spa-sample
> ng build --aot --prod

                                                                                     
Date: 2019-01-09T15:28:37.211Z
Hash: a720188a510b4401014e
Time: 10312ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.e5b8d1357cdaa3ffd936.css (styles) 61.8 kB [initial] [rendered]

ERROR in node_modules/@openid/appauth/built/xhr.d.ts(5,31): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(11,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(17,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
node_modules/@openid/appauth/built/xhr.d.ts(26,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
src/app/html5_requestor.ts(15,28): error TS2304: Cannot find name 'JQueryAjaxSettings'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appauth-angular-app@1.0.0 postinstall: `ng build --aot --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appauth-angular-app@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/75218k@maif.local/.npm/_logs/2019-01-09T15_28_37_260Z-debug.log
```

Any idea on why it's not working?

**Comment by stephanedaviet** [comment]
It is working on commit 2cee38b.

**Comment by dwaite** [comment]
Yes, I believe previous versions of this sample referenced HEAD of the appauth-js library while it was prerelease, while we now reference versioned releases.

**Comment by dwaite** [comment]
It appears that the newest release of AppAuth-JS changed something which broke the build. NPM and Yarn do not have a common package lock format, so you were resolving the newest package.

I recommend changing the version to "1.1.1"; I will probably just remove the html5 requestor once I verify the fetch requestor they added in appauth 1.2.0 is compatible.

**Comment by BouJe** [comment]
Hello, any update on this issue ?
I get the same error even with @openId/AppAuth 1.1.1( and with 1.2.1 as well)

**Comment by ankitoye** [comment]
I am also getting the same error, really need this working. Please help.

**Comment by dwaite** [comment]
Pinning against `1.1.1` works for me. I also deleted the `yarn.lock` and `node_modules` directory and tried with `npm install`

I checked in a new `package.json` and `yarn.lock` which includes both this and updates to newer packages in general.

**Comment by dwaite** [comment]
I have upgraded appauth-js to 1.2.1 (and pinned it to that version in case they make more incompatible changes). @ankitoye, @BouJe , could you verify this resolves your issue?

**Comment by ankitoye** [comment]
Thanks, I will try again and let you know.

**Comment by BouJe** [comment]
I just tryed and I don't have the issue anymore, the app build and start well ! Thank you
