### ISSUE TITLE
PKCE flow is not working when hosted application

### ISSUE THREAD

**Issue by gautbava** [pingidentity/angular-spa-sample#8]
I used this solution and configured to work with our Idp or Secure token service(Ping Federate). codeflow-pkce worked as expected for SSO in locally but when hosted this application, it follows code flow without pkce.

When hosted into our website URL, flow not sending code_challenge and code_challenge_method parameters in the initial request such as follows but working fine in localhost.
https://sso.pingxxx.com/as/authorization.oauth2?redirect_uri=http%3A%2F%2Fl45367.ourdomain.com%3A3009%2Fcallback&client_id=ourapp&response_type=code&state=aANyA446UP&scope=openid&IdpApp=PingNoKerb&response_mode=fragment

**Comment by dwaite** [comment]
Apologies for not responding to this sooner. The code_challenge is being sent in the initial request in my environment, also visible at https://angular-appauth.herokuapp.com/ . Please reopen if this is still an issue.
